### ISSUE TITLE
Kentico.Xperience.Libraries dependency in the admin app

### ISSUE THREAD

**Issue by phixxo** [Kentico/xperience-twilio-sms#4]
Installing the Nuget package will also install the Kentico.Xperience.Libraries package to the admin app which can cause various issues. Moreover, the CMSApp is set to use DLLs from the LIB folder, so whatever is brought to the app by the package, can be overridden after building the project. Also, users must be really careful on the hotfix versions applied, package versions installed, etc. It does not sound like a good practice.

**Comment by seangwright** [comment]
One of the main issues this NuGet package is in use is that teams/partners/customers have made reusable NuGet packages and Kentico did not create an "Admin" or shareable NuGet package for KX13 [like we did for K12 or previous versions](https://www.nuget.org/packages/Kentico.Libraries.Web.UI/) and there wasn't any guidance on how to make these kinds of packages.

**Comment by Sapphirress** [comment]
Thanks Sean for your explanation!
